export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';

export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAIL = 'GET_USER_DETAIL_FAIL';


export const GET_SOFT_LIST = 'GET_SOFT_LIST';
export const GET_SOFT_LIST_SUCCESS = 'GET_SOFT_LIST_SUCCESS';
export const GET_SOFT_LIST_FAIL = 'GET_SOFT_LIST_FAIL';
